export const dynamic = "force-dynamic";

import { Bot, Sparkles, WalletCards } from "lucide-react";

import { RecommendationCard } from "@/components/ai/RecommendationCard";
import { SummaryCard } from "@/components/dashboard/SummaryCard";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { fetchAnalyticsSummary, fetchRecommendations } from "@/lib/api";
import { formatNPR } from "@/lib/utils";

export default async function RecommendationsPage() {
  const [summary, recommendations] = await Promise.all([fetchAnalyticsSummary(), fetchRecommendations()]);
  const highPriority = recommendations.filter((recommendation) => recommendation.priority === "HIGH");
  const totalSavings = recommendations.reduce((sum, recommendation) => sum + recommendation.estimatedSavingNpr, 0);

  return <div className="space-y-6"><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3"><SummaryCard label="AI actions" value={`${recommendations.length}`} helper="Generated from current analytics" icon={Bot} tone="blue" /><SummaryCard label="High priority" value={`${highPriority.length}`} helper="Should be reviewed first" icon={Sparkles} tone="orange" /><SummaryCard label="Savings potential" value={formatNPR(totalSavings)} helper="Projected monthly impact" icon={WalletCards} tone="green" /></section><Card><CardHeader className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div><CardTitle>Recommendation queue</CardTitle><CardDescription>Gemini-ready UI with rule-backed mock recommendations until the backend AI service is connected.</CardDescription></div><Button><Sparkles className="size-4" />Generate new</Button></CardHeader><CardContent><Tabs defaultValue="all" className="gap-5"><TabsList><TabsTrigger value="all">All</TabsTrigger><TabsTrigger value="high">High</TabsTrigger><TabsTrigger value="savings">Cost saving</TabsTrigger></TabsList><TabsContent value="all" className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{recommendations.map((recommendation) => <RecommendationCard key={recommendation.id} recommendation={recommendation} />)}</TabsContent><TabsContent value="high" className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{highPriority.map((recommendation) => <RecommendationCard key={recommendation.id} recommendation={recommendation} />)}</TabsContent><TabsContent value="savings" className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{recommendations.filter((recommendation) => recommendation.type === "cost_saving").map((recommendation) => <RecommendationCard key={recommendation.id} recommendation={recommendation} />)}</TabsContent></Tabs></CardContent></Card><Card><CardHeader><CardTitle>AI context package</CardTitle><CardDescription>Verified analytics values for Gemini context so generated text cannot invent numbers.</CardDescription></CardHeader><CardContent className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><div className="rounded-md border bg-muted/30 p-4"><p className="text-xs text-muted-foreground">Energy</p><p className="mt-2 font-semibold">{summary.totalKwh.toLocaleString("en-NP")} kWh</p></div><div className="rounded-md border bg-muted/30 p-4"><p className="text-xs text-muted-foreground">Cost</p><p className="mt-2 font-semibold">{formatNPR(summary.costNpr)}</p></div><div className="rounded-md border bg-muted/30 p-4"><p className="text-xs text-muted-foreground">Efficiency</p><p className="mt-2 font-semibold">{summary.efficiencyScore}/100</p></div><div className="rounded-md border bg-muted/30 p-4"><p className="text-xs text-muted-foreground">Anomalies</p><p className="mt-2 font-semibold">{summary.anomalyCount}</p></div></CardContent></Card></div>;
}
